### ISSUE TITLE
Allow tests to be run against different versions of kafka broker

### ISSUE THREAD

**Issue by franvila** [ozangunalp/kafka-native#21]
Hi Ozan!

I am working with @k-wall and we would like to discuss with you a topic we have in mind that is very useful for us.

We are very interested in having container images in quay for different versions of kafka-native, because it is important for us to demonstrate that our project works against many versions of the kafka broker. 

Our test framework currently relies on your repo to provide an image containing the kafka native binary. 

We need a mechanism to produce many different kafka-native images (one per kafka version). Perhaps the naming scheme could be:

```
 quay.io/projectName/kafka-native-3.3.1:latest
 quay.io/projectName/kafka-native-3.2.0:latest
```

For that we will appreciate a lot your experience and your work in this repo to help us with our topic. What do you suggest that could be the best approach for that?

**Comment by ozangunalp** [comment]
I see that this has been discussed here: https://github.com/kroxylicious/kproxy/issues/86. So putting it here for xref.

I expected this to become a requirement, just not this fast :) 

It is not as straightforward as creating a kafka broker distribution, because it is compiled. Applied substitutions and some wrapping code can change. I think having a branch per supported kafka version makes sense.

As per the naming scheme, I'd keep the repository name as kafka-native, and change the tag like [project-version|latest]-kafka-[kafka-version], just like https://quay.io/repository/strimzi/kafka?tab=tags or https://quay.io/repository/strimzi-test-container/test-container?tab=tags. So it would be tags like 

```
quay.io/ogunalp/kafka-native:latest-kafka-3.3.1
quay.io/ogunalp/kafka-native:0.1.2-kafka-3.2.0
quay.io/ogunalp/kafka-native:latest-kafka-3.2.1
quay.io/ogunalp/kafka-native:0.1.2-kafka-3.2.1
```

I recently worked on a github actions pipeline to perform a release. Currently, it releases maven artifacts to central and publishes image tags (version and latest) to quay.io. 
We can adapt this to pick several branches, build images for them and push to quay with specific tags.
